<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- 确保以下设置为 false -->
    <PublishAot>false</PublishAot>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
	  <PackageReference Include="Microsoft.Orleans.Server" Version="10.1.0" />
	  <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
	  <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bee.ISS.Abstractions\Bee.ISS.Abstractions.csproj" />
    <ProjectReference Include="..\Bee.ISS.Actors\Bee.ISS.Actors.csproj" />
    <ProjectReference Include="..\Bee.ISS.Domain\Bee.ISS.Domain.csproj" />
    <ProjectReference Include="..\Phenix.Core\Phenix.Core_PgSQL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
	
  <!--<PropertyGroup>
	<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>-->

</Project>
